#!/bin/bash
# For more info see https://golang.org/doc/install.html, the instructions
# there are all that is needed to install Go.
#
# DO NOT RUN with SUDO; Go should be installed under the user not root.
# Using sudo will cause problems.
#
# This script will install Go to /usr/local/go.  The default location for
# your Go workspace ($GOPATH) is $HOME/go.  A custom location can be
# specified using the -w or --workspace flag.
#
# Please see https://golang.org/doc/code.html for more information about
# code organization.

workspace="$HOME/go"

while [[ $# > 0 ]]
do
	case "$1" in
		-h|--help)
			echo ""
			echo "Usage: ./install_current [OPTIONS]"
			echo ""
			echo "  The default workspace location is $HOME/go"
			echo ""
			echo "  -h, --help       print help message"
			echo "  -w, --workspace  specify a custom workspace ($GOPATH)"
			echo ""

			exit 0
			;;
		-w|--workspace)
			workspace="$2"
			;;
	esac
shift
done

mkdir -p "$workspace"
echo export "GOPATH=$workspace" >> "$HOME/.bashrc"
echo export "PATH=$PATH:/usr/local/go/bin:$GOPATH/bin" >> "$HOME/.bashrc"
source "$HOME/.bashrc"

# download and extract Go to /usr/local/go/
# change the tarball for different version/arch
wget -qO- https://storage.googleapis.com/golang/go1.6.3.linux-amd64.tar.gz | sudo tar xz -C /usr/local
