#!/bin/bash
# upgrade to current version

# remove the old Go
sudo rm -rf /usr/local/go

# remove artifacts from prior version
# May not be necessary: commentint out for now
rm -rf $GOPATH/pkg/*

# download and extract Go to /usr/local/go/
# change the tarball for different version/arch
wget -qO- https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz | sudo tar xz -C /usr/local
